import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";
import Image from "next/image";
import bg from "@/public/bg.jpg";

export const metadata = {
    title: "Groovy Stadistics",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <NextUIProvider>
            <div className="relative min-h-screen items-center justify-center">
                <Image
                    src={bg}
                    alt="Background"
                    className="absolute inset-0 -z-20 bg-cover object-cover opacity-10"
                    fill={true}
                    priority
                />
                <div className={'relative z-10'}>
                    {children}
                </div>
            </div>
        </NextUIProvider>
        </body>
        </html>
    );
}
